### ISSUE TITLE
Does not remember settings

### ISSUE THREAD

**Issue by qbancoffee** [shuuryou/imacg3#6] opened 2020-05-17 20:59 UTC
Even if not using the reset switch, it seems to not remember previous settings(at least under mono) and as a result one can never use the advanced options.

**Comment by shuuryou** [comment] 2020-05-18 15:27
I had this happen on Windows, but the other way around (could never turn off advanced options). This may be because I changed a property of the user settings a while back to make them stored in roaming AppData instead of local AppData on Windows.

Can you do `find TAKEMURA` in your home folder and delete any configs that show up? (they are in a folder called something like _TAKEMURA_Kiriko_ because I used a random name in the company name field of AssemblyInfo.cs).

Also make sure the "app.config" file in the directory that contains the EXE does not contain a `<UserSettings>` element or similar (there's a mono bug where it always uses those rather than the actual user settings). If it does, please delete that part from the XML.

**Comment by qbancoffee** [comment] 2020-05-18 16:30
-Deleted all configs in $HOME/.config/TAKEMURA\ Kiriko
-Can't find app.config along with the executable but there is one along with the source files in the "crtcpl" folder.
There are opening and closing tags but nothing in between.

```
<userSettings>
    </userSettings>
```

I ran the program after deleting the configs but it still doesn't remember.

**Comment by shuuryou** [comment] 2020-05-18 16:53
Can you check for a crtcpl.exe.config file in the EXE directory? (I forgot these get renamed on compile)

Does it have the `<userSettings> ... </userSettings>` as well? If that XML node exists, _even if its empty_, Mono refuses to save/load the settings to your user profile.

This issue bit me while testing on Linux and I was about to replace the setting system with a homegrown alternative but then I found this - https://stackoverflow.com/questions/37292416/mono-cant-save-user-settings - which resolved it for me.

**Comment by qbancoffee** [comment] 2020-05-18 17:04
Just checked and "crtcpl.exe.config"  does not have the tags..


`<?xml version="1.0" encoding="utf-8"?>
<configuration>
<configSections>
    <sectionGroup name="userSettings" type="System.Configuration.UserSettingsGroup, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" >
        <section name="crtcpl.Settings" type="System.Configuration.ClientSettingsSection, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" allowExeDefinition="MachineToLocalUser" requirePermission="false" />
    </sectionGroup>
</configSections>
<startup><supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.0,Profile=Client"/></startup>
</configuration>
`

**Comment by shuuryou** [comment] 2020-05-18 21:22
I'm able to reproduce it on Ubuntu. I have no clue what's causing it though. If I run `strace mono crtcpl/bin/Mono/crtcpl.exe 2>&1 | grep TAKEMURA` I can see the settings file being found and opened.

I'll continue to investigate. I can't believe this doesn't work. I mean, yeah, Mono is kind of shitty, but it can't be _that_ bad.

**Comment by qbancoffee** [comment] 2020-05-18 21:30
It really is weird but that said I can confirm that it behaves the same way on raspian.
It was working when you first added it though.

**Comment by shuuryou** [comment] 2020-05-18 22:11
I have no idea why it broke or what will unbreak it or how to prevent it from breaking when the next set of changes get made. :frowning: So instead I just rolled my own settings system. This one is so simple there's not a lot that can fail. It seems to work fine on both Linux and Windows without issues.

Please delete any _TAKEMURA_ folders in your home directory. It should now save at `$HOME/.config/crtcpl/config.xml`.

Please give the updated code in the repo a try and let me know how it works for you. If it doesn't work, running crtcpl with `/log` will log errors that will help to debug the issue.

**Comment by qbancoffee** [comment] 2020-05-19 00:06
I just tested on both my ubuntu machine and on the raspberry pi and it worked!
I would call this issue closed.

**Comment by shuuryou** [comment] 2020-05-19 13:33
Closing this.
Thanks for the feedback. 👍

**Closed as completed by shuuryou** 2020-05-19 13:33 UTC
Labels: bug
